server:
  port: 8085

spring:
  application:
    name: notification-service

  config:
    import: optional:configserver:http://localhost:8888

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    listener:
      simple:
        observation-enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
    zipkin:
      endpoint: http://localhost:9411/api/v2/spans

  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,loggers,trace

  metrics:
    tags:
      application: notification-service

logging:
  pattern:
    level: "%5p [${spring.application.name:},traceId=%X{traceId:-},spanId=%X{spanId:-}]"

  level:
    org.springframework.amqp: DEBUG