server:
  port: 8082

spring:
  application:
    name: member-service
  sql.init.mode: always
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}

  datasource:
    url: jdbc:mysql://localhost:3306/member_db?createDatabaseIfNotExist=true
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: health
