server:
  port: 8083

spring:
  application:
    name: loan-service

  cloud:
    openfeign:
      okhttp:
        enabled: true
      micrometer:
        enabled: true

  config:
    import: optional:configserver:http://localhost:8888

  datasource:
    url: jdbc:mysql://localhost:3306/loan_db?createDatabaseIfNotExist=true
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    listener:
      simple:
        observation-enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  circuitbreaker:
    instances:
      bookServiceBreaker:
        register-health-indicator: true
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-type: COUNT_BASED

management:
  tracing:
    sampling:
      probability: 1.0
    zipkin:
      endpoint: http://localhost:9411/api/v2/spans

  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,loggers,trace,circuitbreakers,circuitbreakerevents

  health:
    circuitbreakers:
      enabled: true

  metrics:
    tags:
      application: loan-service

logging:
  pattern:
    level: "%5p [${spring.application.name:},traceId=%X{traceId:-},spanId=%X{spanId:-}]"